name: tf_Jul2025
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - colorama=0.4.6
  - contourpy=1.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - double-conversion=3.3.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.0
  - freetype=2.13.3
  - graphite2=1.3.14
  - harfbuzz=11.3.2
  - icu=75.1
  - joblib=1.5.1
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=20.1.8
  - libcups=2.3.3
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.5
  - libsqlite=3.50.3
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - munkres=1.1.4
  - ncurses=6.5
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.3
  - packaging=25.0
  - pandas=2.3.1
  - patsy=1.0.1
  - pcre2=10.45
  - pillow=11.3.0
  - pip=25.1.1
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.9.1
  - readline=8.2
  - scikit-learn=1.7.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - statsmodels=0.14.5
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.1
  - tqdm=4.67.1
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wayland=1.24.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zstd=1.5.7
  - pip:
      - flatbuffers==25.2.10
      - keras==3.10.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - namex==0.1.0
      - numpy==2.1.3
      - nvidia-cublas-cu12==12.5.3.2
      - nvidia-cuda-cupti-cu12==12.5.82
      - nvidia-cuda-nvcc-cu12==12.5.82
      - nvidia-cuda-nvrtc-cu12==12.5.82
      - nvidia-cuda-runtime-cu12==12.5.82
      - nvidia-cudnn-cu12==9.3.0.75
      - nvidia-cufft-cu12==11.2.3.61
      - nvidia-curand-cu12==10.3.6.82
      - nvidia-cusolver-cu12==11.6.3.83
      - nvidia-cusparse-cu12==12.5.1.3
      - nvidia-nccl-cu12==2.23.4
      - nvidia-nvjitlink-cu12==12.5.82
      - optree==0.16.0
      - protobuf==5.29.5
      - pygments==2.19.2
      - rich==14.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - typing-extensions==4.14.1
      - wrapt==1.17.2
prefix: /mnt/home/singhp19/.conda/envs/tf_Jul2025
